# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Att',
            fields=[
                ('att_pk', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('index', models.FileField(blank=True, null=True, upload_to='contabilidad.AttIndex/bytes/filename/mimetype')),
            ],
        ),
        migrations.CreateModel(
            name='AttIndex',
            fields=[
                ('att_index_pk', models.AutoField(primary_key=True, serialize=False)),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('idSF', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=20)),
                ('ejecucionPago', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='att',
            name='provision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Provision'),
        ),
    ]
