"""
Django settings for AttachmentSF project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from django.core.urlresolvers import reverse_lazy
from  . import config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # App's 
    'apps.usuario',
    'apps.salesforceMigrate',
    'apps.contabilidad',

    # App's Extension
    'db_file_storage',
    'django_tables2',
    'django_filters',
    'bootstrap3',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AttachmentSF.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AttachmentSF.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ['DEFAULT_ENGINE'],
        'NAME': os.environ['DEFAULT_NAME'],
        'USER': os.environ['DEFAULT_USER'],
        'PASSWORD': os.environ['DEFAULT_PASSWORD'],
        'HOST': os.environ['DEFAULT_HOST'],
        'PORT': os.environ['DEFAULT_PORT'],
    }
    ,'salesforce': {
        'ENGINE': os.environ['SALESFORCE_ENGINE'],
        'CONSUMER_KEY': os.environ['SALESFORCE_CONSUMER_KEY'],
        'CONSUMER_SECRET': os.environ['SALESFORCE_CONSUMER_SECRET'],
        'USER': os.environ['SALESFORCE_USER'],
        #'PASSWORD': os.environ['SALESFORCE_PASSWORD'],
        'PASSWORD': os.environ['SALESFORCE_PASSWORD'],
        'HOST': os.environ['SALESFORCE_HOST'],
    }
}

DATABASE_ROUTERS = [
    'salesforce.router.ModelRouter',
    #'contabilidad.router.ContaEouter',
]

DEFAULT_FILE_STORAGE = 'db_file_storage.storage.DatabaseFileStorage'

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'staticfiles'
#STATIC_ROOT = os.path.normpath(os.path.join(BASE_DIR, 'staticfiles'))

# Defined dir folder for static files
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

# Redirect after login
LOGIN_REDIRECT_URL = reverse_lazy('usuario:home')
LOGOUT_REDIRECT_URL = reverse_lazy('login')

# Defined credentials from account email, for confirmation reset password from user's
EMAIL_USE_TLS = os.environ['EMAIL_USE_TLS']
EMAIL_HOST = os.environ['EMAIL_HOST']
EMAIL_PORT = os.environ['EMAIL_PORT']
EMAIL_HOST_USER = os.environ['EMAIL_HOST_USER']
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']
EMAIL_BACKEND = os.environ['EMAIL_BACKEND']
